### ISSUE TITLE
B站页面布局变化，未找到视频ID或UP主ID

### ISSUE THREAD

**Issue by HanYaodong** [HanYaodong/BilibiliSponsorBlock#1]
如果你发现B站更新了页面布局，导致插件不能正确检测视频ID或者Up主的ID，可以在下面留言。
也请提供你的浏览器和版本，最好能有截图。

**Comment by quaox** [comment]
I am thrilled to come across your work! This project has truly captured my interest :) Your efforts are highly appreciated~

**Comment by HanYaodong** [comment]
> I am thrilled to come across your work! This project has truly captured my interest :) Your efforts are highly appreciated~

Thanks for your support! The project is almost feature complete, so stay tuned for the first release : )
