### ISSUE TITLE
”离题的闲聊/笑话“类别提交失败

### ISSUE THREAD

**Issue by JiunnTarn** [HanYaodong/BilibiliSponsorBlock#13]
### 复现步骤

选中一段视频，选择”离题的闲聊/笑话“类别，点击提交后提示 "400 Category doesn't exist."

似乎是因为服务端没开启 `filler` 类别？

![Snipaste_2024-08-03_19-09-40](https://github.com/user-attachments/assets/22b1c244-983f-4ab3-a6fa-7ee0d375579e)

### 版本

- 浏览器：Vivaldi v6.8.3381.50

- BilibiliSponsorBlock v0.2.1

**Comment by HanYaodong** [comment]
确实是因为没有开启filler类型，现在已经修复。感谢反馈！
