### ISSUE TITLE
对于YouTube和B站上相同的视频，直接使用YouTube上的片段数据

### ISSUE THREAD

**Issue by febilly** [HanYaodong/BilibiliSponsorBlock#2]
有一些up主在油管也有账号，发的视频也是（基本）一样的，那是不是可以用YouTube上对应视频的SponsorBlock的数据来套在B站上？🤔

**Comment by HanYaodong** [comment]
是的，计划相同的视频从原插件服务器里直接拿数据。但是怎么做数据同步还没有想好，两边的视频都有可能涉及到换源；而且对于无法访问YouTube的用户来说，如何确定两个网站的视频是否真的一致也是个麻烦事。

初版应该不会包含这个功能，需要仔细考虑一下各种场景。
