### ISSUE TITLE
兼容性问题：影响 Bilibili-Evolved 的自定义顶栏效果

### ISSUE THREAD

**Issue by ygguorun** [HanYaodong/BilibiliSponsorBlock#8]
单独安装 [Bilibili-Evolved](https://github.com/the1812/Bilibili-Evolved) 的自定义顶栏组件时，顶栏下拉菜单显示正常

![image](https://github.com/HanYaodong/BilibiliSponsorBlock/assets/36809814/ea641c2b-7ce9-4bd3-8258-5a90a66fc9a9)

启用空降助手插件后，下拉菜单显示异常（背景色变透明，下拉菜单相对原始触发文字不居中）

![image](https://github.com/HanYaodong/BilibiliSponsorBlock/assets/36809814/a467813c-f4cf-4d93-b65d-6b22efd51891)

最新版 Chrome 与 FireFox 均存在此问题。因为个人理解空降助手不会对顶栏直接进行操作，所以先在这里进行反馈。

**Comment by HanYaodong** [comment]
解决了，是一些老的全局样式影响到别的页面了。不过插件新版本审核发布还要一段时间。
